### ISSUE TITLE
Error al instalar en XAMPP

### ISSUE THREAD

**Issue by Azzlaer** [Maxelweb/ServerRemoteConsoleSAMP#9]
Hola quisiera saber cual es la solucion a mi problema de instalacion en xampp usando windows

Fatal error: Uncaught Error: Undefined constant "BULL_FOLDER" in C:\xampp\htdocs\samp\1\includes\environment.php:23 Stack trace: #0 C:\xampp\htdocs\samp\1\install.php(24): require() #1 {main} thrown in C:\xampp\htdocs\samp\1\includes\environment.php on line 23

Si en el archivo install.php le quito la linea "require('includes/environment.php');"
La pagina me abre y se visualiza perfectamente pero no se instala :(

**Comment by Azzlaer** [comment]
Acabo de instalar en un webhosting y tambien me dice error:

Fatal error: Uncaught Error: Undefined constant "BULL_FOLDER" in /home/u745993038/domains/d2revenge.com/public_html/samp/includes/environment.php:23 Stack trace: #0 /home/u745993038/domains/d2revenge.com/public_html/samp/install.php(24): require() #1 {main} thrown in /home/u745993038/domains/d2revenge.com/public_html/samp/includes/environment.php on line 23
